USE MICROBIALITES;

DROP TABLE MacrostructurePhoto;
DROP TABLE MesostructurePhoto;
DROP TABLE ThinSectionPhoto;
DROP TABLE Photo;
DROP TABLE AnalyzingMacrostructure;
DROP TABLE AnalyzingMesostructure;
DROP TABLE AnalyzingThinSection;
DROP TABLE ProblemLog;
DROP TABLE Employee; 
DROP TABLE ClasticGrain;
DROP TABLE Minearlogy;
DROP TABLE Porosity;
DROP TABLE Cement;
DROP TABLE Texture;
DROP TABLE ThinSection;
DROP TABLE Mesostructure;
DROP TABLE Macrostructure;
DROP TABLE Waypoint;
